---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: guestbook
  name: redis-secondary-app-placement-1
  labels:
    app: redis-secondary-app
spec:
  clusterSelector:
    matchLabels:
      name: rosa-sbmr2

