apiVersion: v1
kind: Service
metadata:
  name: redis-secondary
  namespace: guestbook
  labels:
    app: redis
    role: secondary
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: secondary
    tier: backend
